export const APP_ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  authCallback: "/auth/callback",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  pricing: "/pricing",
  ccnaCourseSubscription: "/ccna-course-subscription",
  ccnaPracticeTestSubscription: "/ccna-practice-test-subscription",
  ccnaCourseFreeTrial: "/ccna-course-free-trial",
  ccnaCourseWithPracticeTests: "/ccna-course-with-practice-tests",
  ccnaLabSubscription: "/ccna-lab-subscription",
  ccnaPracticeQuestionsNotExamDump: "/ccna-practice-questions-not-exam-dump",
  ccnaPastQuestionsEthicalAlternative: "/ccna-past-questions-ethical-alternative",
  whatIsAllowedForCcnaPractice: "/what-is-allowed-for-ccna-practice",
  bosonExsimCcnaReview: "/boson-exsim-ccna-review",
  measureupCcnaPracticeTestReview: "/measureup-ccna-practice-test-review",
  bosonVsMeasureupCcna: "/boson-vs-measureup-ccna",
  bestWebsiteForCcnaPractice: "/best-website-for-ccna-practice",
  bestCcnaLabs: "/best-ccna-labs",
  bestCcnaPracticeTests: "/best-ccna-practice-tests",
  ccnaTimedPracticeTest: "/ccna-timed-practice-test",
  ccnaMockExam200301: "/ccna-mock-exam-200-301",
  ccnaQuestionBankWithExplanations: "/ccna-question-bank-with-explanations",
  ccnaPracticeTestFreeVsPaid: "/ccna-practice-test-free-vs-paid",
  ccnaLabsWithAnswers: "/ccna-labs-with-answers",
  ccnaLabsForBeginners: "/ccna-labs-for-beginners",
  ccnaPacketTracerLabsDownload: "/ccna-packet-tracer-labs-download",
  ccnaSubnettingPractice: "/ccna-subnetting-practice",
  ccnaLabs: "/ccna-labs",
  ccnaVlanLab: "/ccna-vlan-lab",
  ccnaTrunkingExplained: "/ccna-trunking-explained",
  ccnaOspfSingleAreaExplained: "/ccna-ospf-single-area-explained",
  ccnaAclExplained: "/ccna-acl-explained",
  ccnaNatExplained: "/ccna-nat-explained",
  ccnaSshConfiguration: "/ccna-ssh-configuration",
  ccnaPortSecurityConfiguration: "/ccna-port-security-configuration",
  ccnaPracticeExams: "/ccna-practice-exams",
  ccnaExamTopicsExplained: "/ccna-exam-topics-explained",
  ccnaNetworkFundamentals: "/ccna-network-fundamentals",
  ccnaNetworkAccess: "/ccna-network-access",
  ccnaIpConnectivity: "/ccna-ip-connectivity",
  ccnaIpServices: "/ccna-ip-services",
  ccnaSecurityFundamentals: "/ccna-security-fundamentals",
  ccnaAutomationAndProgrammability: "/ccna-automation-and-programmability",
  tutorRoot: "/tutor",
  tutorSchedule: "/tutor/schedule",
  tutorSessions: "/tutor/sessions",
  bookSession: "/book-session",
  sessions: "/sessions",
  notifications: "/notifications",
  settingsNotifications: "/settings/notifications",
  admin: "/admin",
  adminOperations: "/admin/operations",
  adminOperationsDeliveries: "/admin/operations/deliveries",
  adminOperationsJobs: "/admin/operations/jobs",
  adminOperationsRules: "/admin/operations/rules",
  adminOperationsSubscriptions: "/admin/operations/subscriptions",
  adminCertifications: "/admin/certifications",
  adminCourses: "/admin/courses",
  adminModules: "/admin/modules",
  adminLessons: "/admin/lessons",
  adminQuizzes: "/admin/quizzes",
  adminExamSimulator: "/admin/exam-simulator",
  adminLabs: "/admin/labs",
  adminCliChallenges: "/admin/cli-challenges",
  adminTutors: "/admin/tutors",
  adminPlans: "/admin/plans",
  billing: "/billing",
  checkoutSuccess: "/checkout/success",
  checkoutCancel: "/checkout/cancel",
  recommendations: "/recommendations",
  studyPlan: "/study-plan",
  aiTutor: "/ai-tutor",
  community: "/community",
  dashboard: "/dashboard",
  courses: "/courses",
  subnettingPractice: "/practice/subnetting",
  subnettingCalculator: "/practice/subnetting/calculator",
  labs: "/labs",
  cliPractice: "/cli-practice",
  support: "/support",
  supportNew: "/support/new",
  tutors: "/tutors",
  quizzes: "/quizzes",
  examSimulator: "/exam-simulator"
} as const;

export const AUTH_ROUTES = [
  APP_ROUTES.login,
  APP_ROUTES.signup,
  APP_ROUTES.forgotPassword,
  APP_ROUTES.resetPassword
];
